apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: modela-data-dock
    app.kubernetes.io/part-of: modela
  name: modela-data-dock
rules:
  - apiGroups: ["infra.modela.ai"]
    resources:
      - virtualbuckets
      - connections
      - modelasystems
    verbs:
      - get
      - list
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: modela-data-dock
    app.kubernetes.io/part-of: modela
  name: modela-data-dock
  namespace: modela-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: modela-data-dock
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccount:modela-system:modela-data-dock
    namespace: modela-system

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: modela-data-dock
    app.kubernetes.io/part-of: modela
  name: modela-data-dock
  namespace: modela-system