apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: general-micro
  namespace: modela-catalog
spec:
  resourcesTemplate:
    cpuImage:
      name: modela-cpu-trainer-latest
      namespace: modela-catalog
    gpuImage:
      name: modela-gpu-trainer-latest
      namespace: modela-catalog
    requirements:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m" 